### PR TITLE
Nikola

### PR DESCRIPTION
**Pull request by anonymousvegan**
Crated router page and removed some files.

### CODE REVIEW

**Comment by anonymousvegan** [comment]
Added grid cards for news.

**Comment by anonymousvegan** [comment]
Grid for news and IP address location for country.

**Comment by anonymousvegan** [comment]
everything page and footer completed

**Comment by HamzaGorcevic** [comment]
This branch has conflicts that must be resolved,ne znam zbog cega ali ne mogue da merge-am

**Pull request closed without merging**
